blog/urls.py
from django.urls import path
from .views import render_posts, post_detail, post_sale, post_confirm

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path("<int:post_id>", post_detail, name="post_detail"),
    path("<int:post_id>>", post_sale, name="post_sale"),
     path("<int:post_id>>>", post_confirm, name="post_confirm"),
   
    
]

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.CharField(max_length=100)
    vendedor = models.CharField(max_length=100)
    correo = models.CharField(max_length=100)
    telefono = models.CharField(max_length=9)
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(datetime.date.today)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post": post}) 

def post_sale(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_sale.html', {"post": post})

def post_confirm(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_confirm.html', {"post": post})
   

blog/templates/post_confirm.html

{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    
<p class="my-2 h5 text-muted">¡Ya casi es tuyo!</p><br>
<p>Coordina con el vendedor el pago y capacitación.</p><br>
<h5>Información del vendedor</h5>
<span><i class="fa fa-user"></i> {{post.vendedor}}</span></br>
<span><i class="fa fa-phone"></i> 0{{post.telefono}}</span></br>
<span><i class="fa fa-envelope"></i> {{post.correo}}</span>
</br>
<div clas="boton">
<a href="https://api.whatsapp.com/send?phone=593{{ post.telefono }}&text=Hola%21%20Quisiera%20m%C3%A1s%20informaci%C3%B3n%20sobre%20Facturas%20Electrónicas"  target="_blank"><i class="fab fa-whatsapp"></i></a>
</div>
<br>



<img class="img-fluid img-post" width="25%" src="{{post.image.url}}" alt="{{post.title}}"><br>
<p class="my-2 h5 text-muted">Detalles de tu compra</p>
<p>{{post.title}}</p>
<p class="text-success"><strong>Precio $ {{post.price}}</strong></p>




<a class="btn btn-primary" href="/">Finalizar Compra</a>

</div>

{% endblock %}

blog/templates/post_detail.html

{% extends 'layout.html' %}

{% block content %}

</br></br></br>
<div class="row">
<div class="col-md-6 p-4">
    <img class="card img-post" width="50%" src="{{post.image.url}}" alt="{{post.title}">
</div>
<div class="col-md-6 my-auto">
    <h1><strong>{{post.title}}</strong> </h1>
    <h3 class="text-success"><strong>Precio $ {{post.price}}</strong></h3>
    <h3 class="my-2 h5 text-muted">Publicado: {{post.date}}</h3>
    <p>{{post.description|safe}}</p>
    <a class="btn btn-outline-primary" href="/blog">⏎ Regresar</a>
<a class="btn btn-primary" href="{% url 'blog:post_sale' post.id %}">Comprar ahora</a>
    
</div>
</div>






{% endblock %}

blog/templates/post_sale.html

{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <br><br>
    
<h2>Acuerdas el pago y capacitación con el vendedor</h2>
<p>Luego de confirmar tu compra, tendrás que contactarlo para acordar el pago y la entrega del servicio.<p>

<a class="btn btn-primary" href="{% url 'blog:post_confirm' post.id %}">Ok. entiendo</a>
</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}


<h1>Planes</h1>

{% for post in posts %}
<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img class="img-fluid img-post" src="{{post.image.url}}" alt="{{post.title}}" />
            </div>
            
            <div class="col-9">
    
                <h2 class="center">{{post.title}}</h2>
                <p class="center text-success"><strong>Precio $ {{post.price}}</strong></p>
               
                <h3 class="my-2 h5 text-muted">Publicado: {{post.date}}</h3>
                               
                
                <a class="btn btn-primary" href="{% url 'blog:post_detail' post.id %}">Ver detalle</a>
                
            </div>
        </div>
    </div>
</div>
{% endfor%}
{% endblock %}